namespace SunamoValues;

public static class AllStrings
{
    public const string dot = ".";
    public const string comma = ",";
    public const string swes = " = ";
    public const string swda = " - ";
    public const string dash = "-";
    public const string q = "?";
    public const string dd = "..";
    public const string dds = "../";
    public const string ds = "./";
    public const string dotSpace = ". ";
    public const string slashAsterisk = "/*";
    public const string asteriskSlash = "*/";
    public const string apostrophe = "'";
    public const string us = "_";
    public const string space = " ";
    public const string lb = "(";
    public const string rb = ")";
    public const string tab = "\t";
    public const string nl = "\n";
    public const string cr = "\r";
    public const string bs = @"\";
    public const string slash = "/";
    public const string asterisk = "*";
    public const string sc = ";";
    public const string qm = "\"";
    public const string doubleSpace = "  ";
    public const string period = ".";
    public const string colon = ":";
    public const string excl = "!";
    public const string apos = "'";
    public const string quest = "?";
    public const string rpar = ")";
    public const string lpar = "(";
    public const string sol = "/";
    public const string lowbar = "_";
    public const string lt = "<";
    public const string equals = "=";
    public const string gt = ">";
    public const string amp = "&";
    public const string lcub = "{";
    public const string rcub = "}";
    public const string lsqb = "[";
    public const string verbar = "|";
    public const string semi = ";";
    public const string commat = "@";
    public const string ast = "*";
    public const string plus = "+";
    public const string rsqb = "]";
    public const string num = "#";
    public const string percnt = "%";
    public const string dollar = "$";
    public const string Hat = "^";
    public static readonly string swd = " - ";
    public static readonly string cs = ", ";
    public static readonly string cs2 = ": ";
    public static readonly string doubleBs = bs + bs;
}
