name: Build SunamoValues

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoValues
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoValues/SunamoValues.csproj

    - name: Build
      run: dotnet build SunamoValues/SunamoValues.csproj --configuration Release --no-restore

  test:
    name: Test SunamoValues.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoValues.Tests/SunamoValues.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoValues.Tests/SunamoValues.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoValues.Tests/SunamoValues.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
